export const deitiesDict = {
    "Axar": {
        "name": "Axar",
        "category": "Elven Gods",
        "edicts": "Take the finest or healthiest specimen among any animals you hunt, respect your prey, protect your community, show bravery in the face of danger",
        "anathema": "Waste the animals you hunt, show cruelty to animals, abandon your community in a time of danger",
        "areasOfConcern": "Heroism, hunting, pride, tracking, trophies",
        "sacredSymbol": "Snake curling around a rapier",
        "sacredAnimal": "Snake",
        "sacredColor": "Blue, yellow",
        "attribute": ["str", "dex"],
        "fonts": ["heal"],
        "sanctifications": ["holy", "no"],
        "skill": "survival",
        "favoredWeapon": "longbow",
        "domains": ["ambition", "confidence", "protection", "zeal"],
        "spells": {1: "vanishing tracks", 3: "haste", 4: "weapon storm"},
    },
    "Skode": {
        "name": "Skode",
        "category": "Giant Gods",
        "edicts": "Take the finest or healthiest specimen among any animals you hunt, respect your prey, protect your community, show bravery in the face of danger",
        "anathema": "Waste the animals you hunt, show cruelty to animals, abandon your community in a time of danger",
        "areasOfConcern": "Heroism, hunting, pride, tracking, trophies",
        "sacredSymbol": "Sun rising over ocean",
        "sacredAnimal": "Osprey",
        "sacredColor": "Blue, yellow",
        "attribute": ["str", "dex"],
        "fonts": ["heal"],
        "sanctifications": ["holy", "no"],
        "skill": "survival",
        "favoredWeapon": "longbow",
        "domains": ["ambition", "confidence", "protection", "zeal"],
        "spells": {1: "vanishing tracks", 3: "haste", 4: "weapon storm"},
    }
}